name: Pre-release deployment
run-name: ${{ github.actor }} is testing out Github Checks! Fingers crossed again 🚀

on:
  push:
    branches-ignore:
    - master
    - main

jobs:
  prerelease:
    name: Prerelease
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GH_TOKEN }}

    - name: Conventional Changelog Action
      id: changelog
      uses: TriPSs/conventional-changelog-action@v3
      with:
        github-token: ${{ secrets.GH_TOKEN }}
        git-path: charts/deployment
        git-user-name: myonlinestore-ci-eu
        git-user-email: myonlinestore-ci-eu@myonlinstore.com
        tag-prefix: deployment-
        output-file: CHANGELOG.md
        preset: "conventionalcommits"
        release-count: "0"
        skip-ci: false
        version-file: './version.yaml'
        version-path: 'version'

    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GH_TOKEN }}
        commit-message: Auto Pull Request
        branch: ${{ github.ref }} # The branch where you commit
        base: main # Don't forget to specify the right base branch here
        title: '[Example] Update report'
        body: |
            Update report
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]
            Changelog: ${{ steps.changelog.outputs.changelog }}
            Version: ${{ steps.changelog.outputs.version }}
            Tag: ${{ steps.changelog.outputs.tag }}
            Skipped: ${{ steps.changelog.outputs.skipped }}
            ${{ steps.changelog.outputs }}
            
            [1]: https://github.com/peter-evans/create-pull-request
        labels: |
            report
            automated pr
            ${{ steps.changelog.outputs.tag }}
