name: Pre-release deployment
run-name: ${{ github.actor }} is testing out Github Checks! Fingers crossed again 🚀

on:
  push:
    branches-ignore:
    - master
    - main

jobs:
  prerelease:
    name: Prerelease
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GH_TOKEN }}

    - name: Conventional Changelog Action
      id: changelog
      uses: TriPSs/conventional-changelog-action@v3
      with:
        github-token: ${{ secrets.GH_TOKEN }}
        git-path: charts/deployment
        git-user-name: myonlinestore-ci-eu
        git-user-email: myonlinestore-ci-eu@myonlinstore.com
        tag-prefix: deployment-
        output-file: charts/deployment/CHANGELOG.md
        preset: "conventionalcommits"
        release-count: "0"
        skip-ci: false
        version-file: './charts/deployment/Chart.yaml'
        version-path: 'version'
        skip-version-file: true
        skip-commit: true
        skip-tag: true