name: TagFixer
run-name: ${{ github.actor }} is testing out Github Checks! Fingers crossed again 🚀

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  tagfix:
    name: tagfix
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        ref: ${{ github.head_ref }}
    - id: files
      uses: jitterbit/get-changed-files@v1
    - name: Update Tags
      run: |
        for changed_file in ${{ steps.files.outputs.all }}; do
          filename=$changed_file
          dockerfile=${filename%%/*}
          if [ ! $dockerfile == ".github" ]; then
            line1=$(awk 'NR==1' $filename)
            line2=$(awk 'NR==2' $filename)
            oldtag=${line1#*:}
            oldtag=$(echo $oldtag | tr -d ' ')
            newtag=${line2#*:}
            echo "$dockerfile: $oldtag -> $newtag"

            if [ "$oldtag" = "$newtag" ]; then
                echo "Tags are equal."
            else
                echo "Tags are not equal, updating now"
                sed -i -e 1d $filename
                echo -e "# tag: $newtag\n$(cat $filename)" > $filename
            fi
            echo "======================="
          fi
        done
    - name: Commit Tags
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Updated tags
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}