name: TagFixer
run-name: ${{ github.actor }} is testing out Github Checks! Fingers crossed again 🚀

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  tagfix:
    name: tagfix
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - id: files
      uses: jitterbit/get-changed-files@v1
    - run: |
        for changed_file in ${{ steps.files.outputs.all }}; do
          
          filename=$changed_file
          dockerfile=${filename%/*}
          echo $dockerfile
          if [ ! $dockerfile == ".github" ]; then
            line1=$(awk 'NR==1' $filename)
            line2=$(awk 'NR==2' $filename)
            oldtag=${line1#*:}
            oldtag=$(echo $oldtag | tr -d ' ')
            newtag=${line2#*:}
            echo "$dockerfile: $oldtag -> $newtag"

            if [ "$oldtag" = "$newtag" ]; then
                echo "Tags are equal."
            else
                echo "Tags are not equal, updating now"
                sed -i -e 1d $filename
                echo -e "# tag: $newtag\n$(cat $filename)" > $filename
            #    git add $filename
            #    git commit -m "Fixed tag"
            fi
            echo "======================="
          fi
        done