name: TagFixer
run-name: ${{ github.actor }} is testing out Github Checks! Fingers crossed again 🚀

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  tagfix:
    name: tagfix
    runs-on: ubuntu-latest
    steps:
    - id: files
      uses: jitterbit/get-changed-files@v1
    - run: |
        for changed_file in ${{ steps.files.outputs.all }}; do
          echo "Do something with this ${changed_file}."
        done