name: TagFixer
run-name: "chore(deps): Bump tags in Dockerfile"

on:
  workflow_dispatch:
  pull_request:
    types: [opened]
    branches: [main]

jobs:
  tagfix:
    if: ${{ github.actor == 'pimvandenbroek' }}
    name: tagfix
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        ref: ${{ github.head_ref }}
        token: ${{ secrets.GH_TOKEN}}
    - id: files
      uses: jitterbit/get-changed-files@v1
    - name: Update Tags
      id: update_tags
      run: |
        for changed_file in ${{ steps.files.outputs.all }}; do
          filename=$changed_file
          dockerfile=${filename%%/*}
          if [ ! $dockerfile == ".github" ]; then
            line1=$(awk 'NR==1' $filename)
            line2=$(awk 'NR==2' $filename)
            oldtag=${line1#*:}
            oldtag=$(echo $oldtag | tr -d ' ')
            newtag=${line2#*:}
            echo "result=$dockerfile: $oldtag -> $newtag" >> $GITHUB_OUTPUT

            if [ "$oldtag" = "$newtag" ]; then
                echo "$dockerfile: Tags are equal."
            else
                echo "$dockerfile: Tags are not equal, updating now"
                sed -i -e 1d $filename
                echo -e "# tag: $newtag\n$(cat $filename)" > $filename
            fi
            echo "======================="
          fi
        done
    - name: Commit Tags
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Updated tags
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    - uses: mshick/add-pr-comment@v2
      with:
        message: |
          ${{join(steps.update_tags.outputs.*, '\n')}}